### PR TITLE
[WIP] Show fee estimation in vtt 

### PR DESCRIPTION
**Pull request by Tommytrg**
- Add styles similar to Sheikah's
- Use selected fee type while creating the VTT
- Remove old Weighted / Absolute

### CODE REVIEW

**Comment by Tommytrg** [comment]
@parodyBit are the imports sorted in a particular way?

**Comment by parodyBit** [comment]
@Tommytrg 
imports i try to sort by:
1 - flutter/dart native, 
2 - third party packages, 
3 - local wallet imports, 
alphabetical for each

**Comment by Tommytrg** [comment]
This PR is blocked until the estimation feature is implemented in the block explorer

**Comment by drcpu-github** [comment]
> This PR is blocked until the estimation feature is implemented in the block explorer

A priority endpoint has been implemented in the [v1.3 branch](https://github.com/drcpu-github/witnet-explorer-backend/pull/8) of the explorer. It will be merged into the main branch after the [protobuf PR](https://github.com/drcpu-github/witnet-explorer-backend/pull/7) from @parodyBit is finished and everything has been properly tested.

**Pull request closed without merging**
